import { Box } from "@chakra-ui/react";
import { keyframes } from "@emotion/react";

/**
 * The page's colour, taken from the artwork rather than from one value off it.
 *
 * Apple Music's background is not a gradient — it is the album cover itself,
 * several times over, twisted and blurred until it stops being a picture and
 * becomes a light source. Four copies at 25%, 50%, 80% and 125% of the width:
 * the two small ones travel a circular track while they turn, the two large ones
 * turn where they are. The cover is oversaturated on the way in, because a blur
 * averages colour towards grey and the saturation has to be put back.
 *
 * The one thing not reproduced here is the twist — a shader that rotates the
 * image around a point by an angle that grows with distance from it, which CSS
 * has no equivalent for. Blur at this radius does most of the same work: past a
 * certain point neither is legible as a cover any more, which is the point.
 *
 * Rendered blurred as a group rather than per copy. Four separate blur passes
 * cost four times as much for a difference nobody can see through a mask that is
 * already throwing away most of the layer.
 */

/**
 * The falloff, eased the way the eye reads brightness rather than the way a
 * gradient interpolates.
 *
 * Perceived brightness is roughly the cube root of luminance — a patch at 18% of
 * a reference luminance looks about half as bright, not a fifth. So a mask whose
 * alpha falls in a straight line does not look like a straight fade: it drops
 * away fast at the top and then lingers near the bottom, and the eye finds the
 * point where it finally reaches zero. That edge is what the four stop version
 * of this had.
 *
 * Two corrections, then. The fade is shaped with a smoothstep so neither end has
 * a corner in it, and the result is cubed to undo the eye's cube root, so what
 * falls evenly is the brightness somebody actually sees rather than the number
 * in the alpha channel.
 *
 * Built from eighteen stops because the curve has to be approximated by straight
 * segments either way, and a handful of them bands visibly on a dark page.
 */
const FALLOFF = (() => {
    const STOPS = 18;

    const stops = Array.from({ length: STOPS + 1 }, (_, step) => {
        const t = step / STOPS;

        // Smoothstep: flat at both ends, steepest in the middle
        const eased = t * t * (3 - 2 * t);

        const alpha = Math.pow(1 - eased, 3);

        return `rgba(0, 0, 0, ${alpha.toFixed(4)}) ${(t * 100).toFixed(1)}%`;
    });

    return `linear-gradient(to bottom, ${stops.join(", ")})`;
})();

/**
 * Film grain, laid over the wash.
 *
 * Two jobs. It puts a surface on what is otherwise a very smooth, very large
 * area of colour — and it dithers. An eight bit gradient across a dark page has
 * fewer distinct values available than it has pixels to cross, so it steps, and
 * the eye is unusually good at spotting those steps in the dark. Noise breaks
 * the steps into something the eye reads as continuous, which is the same trick
 * print has used for a century.
 *
 * Generated by the browser from an SVG filter rather than shipped as an image:
 * it is a few hundred bytes of markup instead of a texture to download, and it
 * tiles seamlessly because feTurbulence is told to stitch.
 *
 * One octave, not four. Every extra octave in feTurbulence adds a component at
 * *half* the frequency, so stacking them does not make the noise finer — it
 * lays progressively larger blobs over it, and large blobs at this opacity read
 * as a compression artefact rather than as grain. Grain wants a single high
 * frequency and nothing else.
 *
 * Drawn at 200 and tiled at 100, so the texture is downsampled two to one. On a
 * 2x screen that lands one noise texel on one device pixel, which is as fine as
 * grain can be before it stops being visible at all. Tiled at its natural size
 * every texel would cover four device pixels, and chunky noise is most of what
 * makes an overlay look cheap.
 *
 * Deliberately outside the blur — grain that has been blurred is not grain.
 */
const GRAIN = `url("data:image/svg+xml,${encodeURIComponent(
    `<svg xmlns='http://www.w3.org/2000/svg' width='200' height='200'>` +
    `<filter id='g'>` +
    `<feTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='1' stitchTiles='stitch'/>` +
    `<feColorMatrix type='saturate' values='0'/>` +
    `<feComponentTransfer><feFuncA type='linear' slope='1.15' intercept='-0.06'/></feComponentTransfer>` +
    `</filter>` +
    `<rect width='100%' height='100%' filter='url(#g)'/>` +
    `</svg>`,
)}")`;

const turn = keyframes`
    from { transform: rotate(0deg); }
    to   { transform: rotate(360deg); }
`;

const turnBack = keyframes`
    from { transform: rotate(0deg); }
    to   { transform: rotate(-360deg); }
`;

// Rotating *then* translating walks the copy around a circle, and because the
// rotation is not undone afterwards the copy turns as it goes — which is what
// the two small layers do
const orbitNear = keyframes`
    from { transform: rotate(0deg) translateX(16%); }
    to   { transform: rotate(360deg) translateX(16%); }
`;

const orbitFar = keyframes`
    from { transform: rotate(0deg) translateX(26%); }
    to   { transform: rotate(-360deg) translateX(26%); }
`;

const LAYERS = [
    { size: 125, animation: turn, duration: 34, opacity: 0.5 },
    { size: 80, animation: turnBack, duration: 26, opacity: 0.45 },
    { size: 50, animation: orbitNear, duration: 17, opacity: 0.42 },
    { size: 25, animation: orbitFar, duration: 13, opacity: 0.4 },
];

/*
 * The colour, carried separately from the cover.
 *
 * Blurring a sleeve averages it, and the average of most sleeves is a brown. The
 * palette is picked for the opposite of that — the few colours that make the
 * record look like itself — and painted as blobs underneath the cover copies, so
 * the wash keeps the shape and movement of the artwork while taking its colour
 * from something chosen rather than from whatever the blur happened to leave.
 */
const BLOBS = [
    { size: 115, left: 26, top: 22, animation: orbitNear, duration: 19 },
    { size: 98, left: 74, top: 34, animation: turnBack, duration: 25 },
    { size: 88, left: 44, top: 74, animation: orbitFar, duration: 15 },
    { size: 74, left: 82, top: 76, animation: turn, duration: 22 },
];

export function ArtworkWash({ src, palette, still }: Readonly<{ src: string; palette: string[]; still?: boolean }>) {
    return (
        <Box
            position="absolute"
            inset="0"
            overflow="hidden"
            sx={{
                /*
                 * The falloff. Masked rather than faded with a gradient on top,
                 * so the page underneath shows through instead of the wash being
                 * mixed into one particular background colour — which is what
                 * lets this sit over the page rather than in front of it.
                 */
                maskImage: FALLOFF,
                WebkitMaskImage: FALLOFF,
            }}
        >
            <Box
                position="absolute"
                inset="0"
                sx={{
                    filter: "blur(46px) saturate(1.85)",
                    // The blur eats into the edges, so the group is scaled past
                    // them — otherwise the wash has visibly soft corners where it
                    // should run off the side of the page
                    transform: "scale(1.35)",
                }}
            >
                {palette.map((colour, index) => {
                    const blob = BLOBS[index % BLOBS.length];

                    return (
                        <Box
                            key={colour + index}
                            position="absolute"
                            left={`${blob.left}%`}
                            top={`${blob.top}%`}
                            width={`${blob.size}%`}
                            sx={{
                                aspectRatio: "1",
                                translate: "-50% -50%",
                                background: `radial-gradient(circle closest-side, ${colour} 0%, ${colour}00 72%)`,
                                animation: `${blob.animation} ${blob.duration}s linear infinite`,
                                animationPlayState: (still ? "paused" : "running"),
                                willChange: "transform",
                                "@media (prefers-reduced-motion: reduce)": { animation: "none" },
                            }}
                        />
                    );
                })}

                {LAYERS.map(layer => (
                    <Box
                        key={layer.size}
                        position="absolute"
                        top="50%"
                        left="50%"
                        width={`${layer.size}%`}
                        marginLeft={`-${layer.size / 2}%`}
                        // Square, off its own width, so a copy is a cover rather
                        // than a band of one
                        _before={{
                            content: '""',
                            display: "block",
                            paddingTop: "100%",
                        }}
                        marginTop={`-${layer.size / 2}%`}
                        /*
                         * The cover carries the whole wash on its own when there
                         * was no colour worth pulling off it — a black and white
                         * sleeve gets a grey wash rather than an invented hue, and
                         * at blob strength that came out as almost nothing at all
                         */
                        opacity={Math.min(1, layer.opacity * (palette.length > 0 ? 1 : 1.9))}
                        backgroundImage={`url(${src})`}
                        backgroundSize="cover"
                        backgroundPosition="center"
                        sx={{
                            animation: `${layer.animation} ${layer.duration}s linear infinite`,
                            animationPlayState: (still ? "paused" : "running"),
                            willChange: "transform",
                            "@media (prefers-reduced-motion: reduce)": {
                                animation: "none",
                            },
                        }}
                    />
                ))}
            </Box>

            {/*
              * Set through `style` rather than `sx`. Chakra resolves background
              * shorthands against the theme on the way through, and a data URI
              * this long comes out the other side as nothing at all.
              */}
            <Box
                position="absolute"
                inset="0"
                pointerEvents="none"
                style={{
                    backgroundImage: GRAIN,
                    backgroundSize: "100px 100px",
                    // Overlay rather than a flat wash of noise, so the grain
                    // lifts and darkens what is under it instead of greying it
                    mixBlendMode: "overlay",
                    opacity: 0.38,
                }}
            />
        </Box>
    );
}
